package com.sitepk.hibernate;

// Generated 2010-12-23 3:02:45 by Hibernate Tools 3.3.0.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * SpSite generated by hbm2java
 */
@Entity
@Table(name = "sp_site")
@XmlRootElement(name = "site")
@XmlAccessorType(XmlAccessType.FIELD)
public class SpSite implements java.io.Serializable {

	private String siteid;
	private String url;
	private String name;
	private String description;
	private BigDecimal rating;
	private Integer rateUserCount;
	private BigDecimal price;
	private String lan;
	private String country;
	@XmlTransient
	private Set<SpSitetags> spSitetagses = new HashSet<SpSitetags>(0);

	public SpSite() {
	}

	public SpSite(String siteid) {
		this.siteid = siteid;
	}

	public SpSite(String siteid, String url, String name, String description,
			BigDecimal rating, Integer rateUserCount, BigDecimal price,
			String lan, String country, Set<SpSitetags> spSitetagses) {
		this.siteid = siteid;
		this.url = url;
		this.name = name;
		this.description = description;
		this.rating = rating;
		this.rateUserCount = rateUserCount;
		this.price = price;
		this.lan = lan;
		this.country = country;
		this.spSitetagses = spSitetagses;
	}

	@Id
	@Column(name = "SITEID", unique = true, nullable = false, length = 13)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	@Column(name = "URL", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "RATING", precision = 4)
	public BigDecimal getRating() {
		return this.rating;
	}

	public void setRating(BigDecimal rating) {
		this.rating = rating;
	}

	@Column(name = "RATE_USER_COUNT", precision = 8, scale = 0)
	public Integer getRateUserCount() {
		return this.rateUserCount;
	}

	public void setRateUserCount(Integer rateUserCount) {
		this.rateUserCount = rateUserCount;
	}

	@Column(name = "PRICE", precision = 18)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "LAN", length = 5)
	public String getLan() {
		return this.lan;
	}

	public void setLan(String lan) {
		this.lan = lan;
	}

	@Column(name = "COUNTRY", length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spSite")
	public Set<SpSitetags> getSpSitetagses() {
		return this.spSitetagses;
	}

	public void setSpSitetagses(Set<SpSitetags> spSitetagses) {
		this.spSitetagses = spSitetagses;
	}

}
