package com.sitepk.hibernate;

// Generated 2010-12-23 3:02:45 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * SpSitetagsId generated by hbm2java
 */
@Embeddable
@XmlRootElement(name = "sitetagsId")
@XmlAccessorType(XmlAccessType.FIELD)
public class SpSitetagsId implements java.io.Serializable {

	private String id;
	private String siteid;

	public SpSitetagsId() {
	}

	public SpSitetagsId(String id, String siteid) {
		this.id = id;
		this.siteid = siteid;
	}

	@Column(name = "ID", nullable = false, length = 13)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "SITEID", nullable = false, length = 13)
	public String getSiteid() {
		return this.siteid;
	}

	public void setSiteid(String siteid) {
		this.siteid = siteid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpSitetagsId))
			return false;
		SpSitetagsId castOther = (SpSitetagsId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getSiteid() == castOther.getSiteid()) || (this
						.getSiteid() != null
						&& castOther.getSiteid() != null && this.getSiteid()
						.equals(castOther.getSiteid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getSiteid() == null ? 0 : this.getSiteid().hashCode());
		return result;
	}

}
