package com.sitepk.hibernate;

// Generated 2010-12-23 3:02:45 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * SpTags generated by hbm2java
 */
@Entity
@Table(name = "sp_tags")
@XmlRootElement(name = "tags")
@XmlAccessorType(XmlAccessType.FIELD)
public class SpTags implements java.io.Serializable {

	private String tagname;
	private Character isclosed;
	private Integer total;
	@XmlTransient
	private Set<SpSitetags> spSitetagses = new HashSet<SpSitetags>(0);

	public SpTags() {
	}

	public SpTags(String tagname) {
		this.tagname = tagname;
	}

	public SpTags(String tagname, Character isclosed, Integer total,
			Set<SpSitetags> spSitetagses) {
		this.tagname = tagname;
		this.isclosed = isclosed;
		this.total = total;
		this.spSitetagses = spSitetagses;
	}

	@Id
	@Column(name = "TAGNAME", unique = true, nullable = false, length = 20)
	public String getTagname() {
		return this.tagname;
	}

	public void setTagname(String tagname) {
		this.tagname = tagname;
	}

	@Column(name = "ISCLOSED", length = 1)
	public Character getIsclosed() {
		return this.isclosed;
	}

	public void setIsclosed(Character isclosed) {
		this.isclosed = isclosed;
	}

	@Column(name = "TOTAL", precision = 8, scale = 0)
	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spTags")
	public Set<SpSitetags> getSpSitetagses() {
		return this.spSitetagses;
	}

	public void setSpSitetagses(Set<SpSitetags> spSitetagses) {
		this.spSitetagses = spSitetagses;
	}

}
